name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create .env file
      run: |
        mkdir -p src
        cat > src/.env << EOL
        APP_NAME="Ozby's Chatbot"
        APP_DESCRIPTION="An intelligent chatbot powered by FastAPI and modern AI"
        APP_VERSION="0.1"
        CONTACT_NAME="Ozby"
        CONTACT_EMAIL="ozberk@gmail.com"
        LICENSE_NAME="MIT"

        POSTGRES_USER="postgres"
        POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
        POSTGRES_SERVER="db"
        POSTGRES_PORT=5432
        POSTGRES_DB="fastapi_chatbot"

        PGADMIN_DEFAULT_EMAIL="ozberk@gmail.com"
        PGADMIN_DEFAULT_PASSWORD="${{ secrets.PGADMIN_PASSWORD }}"
        PGADMIN_LISTEN_PORT=80

        SECRET_KEY="${{ secrets.SECRET_KEY }}"
        ALGORITHM="HS256"
        ACCESS_TOKEN_EXPIRE_MINUTES=30
        REFRESH_TOKEN_EXPIRE_DAYS=7

        ADMIN_NAME="Admin User"
        ADMIN_EMAIL="ozberk@gmail.com"
        ADMIN_USERNAME="admin"
        ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}"

        REDIS_CACHE_HOST="redis"
        REDIS_CACHE_PORT=6379
        CLIENT_CACHE_MAX_AGE=30
        REDIS_QUEUE_HOST="redis"
        REDIS_QUEUE_PORT=6379
        EOL

    - name: Build and test
      run: |
        chmod +x run.sh
        ./run.sh rebuild
        ./run.sh logs

    - name: Check if containers are running
      run: |
        docker compose ps
        docker compose logs
